general:
  database:
    sqltype: sqlite
    client: psycopg2
    user_name: postgres
    password: 1234
    host: localhost
    port: 5432
    db_name: historic
  operation_settings:
    frequency: 0.1
  utilities:
    yaml_path: resources/running_exchanges/all/
    enable_logging: false

jobs:
  Ticker:
    yaml_request_name: trades

    update_cp: false
    exchanges:
      - btc-alpha
      - bibox
      - aax
      - bidesk

    currency_pairs:
#      - all
#      - first: cur
#        second: eth
#      - first: btc
#        second: usdt
      - first: btc
        second: usdt
#      - first: btc
#        second: usd
#      - first: eth
#        second: btc
#
    first_currencies:
    second_currencies:
