general:
  database:
    sqltype: sqlite
    client: psycopg2
    user_name: postgres
    password: 1234
    host: localhost
    port: 5432
    db_name: historic
  operation_settings:
    frequency: once
    run_once: true
  export:
    export_data_to_csv: false
    csv_dir: resources/csv
  utilities:
    yaml_path: resources/running_exchanges/all/
    enable_logging: false

jobs:
  Ticker:
    yaml_request_name: historic_rates

    update_cp: false
    exchanges:
      - btc-alpha
#      - atilly
      - hitbtc
      - binance
      - bitfinex
    currency_pairs:
#      - all
#      - first: cur
#        second: eth
#      - first: btc
#        second: usdt
#      - first: btc
#        second: usdt
#      - first: eth
#        second: usd
      - first: eth
        second: btc
#
    first_currencies:
    second_currencies:
