general:
  database:
    sqltype: sqlite
    client: psycopg2
    user_name: postgres
    password: 1234
    host: localhost
    port: 5432
    db_name: historic
  operation_settings:
    frequency: 0.1
    timeout: 100
  utilities:
    yaml_path: resources/running_exchanges/all/
    enable_logging: true

jobs:
  Ticker:
    yaml_request_name: order_books

    update_cp: false
    exchanges:
#      - all
      - btc-alpha
#      - atilly
      - hitbtc
      - binance
      - bibox
    currency_pairs:
#      - all
#      - first: btc
#        second: usd
#      - first: btc
#        second: usdt
      - first: eth
        second: btc
#
    first_currencies:
    second_currencies:
