general:
  database:
    sqltype: postgresql
    client: psycopg2
    user_name: bjarne
    password: ""
    host: localhost
    port: 5432
    db_name: hochfrequenz

  utilities:
    yaml_path: resources/hr_exchanges/tested/test/working/

jobs:
  collecting_ticker:
    yaml_request_name:
      first: ticker
      second: ticker
    frequency: 5
    exchanges:
      - binance
      - bibox
    currency_pairs:
      - first: btc
        second: eth
      - first: eth
        second: doge

    first_currency:
    second_currency:
