general:
  database:
    sqltype: postgresql
    client: psycopg2
    user_name: postgres
    password: Thw_kiel
    host: localhost
    port: 5432
    db_name: hochfrequenz
  operation_settings:
    frequency: 1
  export:
    export_data_to_csv: false
    csv_dir: /path/where/to/save/csv
  utilities:
    yaml_path: resources/running_exchanges/testing/working/
    enable_logging: True



jobs:
#
#  tickers:
#    yaml_request_name: ticker
#    update_cp: False
#    exchanges:
##      - exmo
##      - bibox
#      - binance
#    currency_pairs:
#      - first: btc
#        second: usd
#      - first: ltc
#        second: btc
#    first_currencies:
#      - btc
#    second_currencies:
#
#  historic_rates:
#    yaml_request_name: historic_rates
#    update_cp: False
#    exchanges:
#      - bibox
#    currency_pairs:
#      - first: eth
#        second: btc
#    first_currencies:
##      - btc
#    second_currencies:
##      - eth


  order_books:
    yaml_request_name: order_books
    update_cp: False
    exchanges:
      - binance
    currency_pairs:
      - first: ltc
        second: btc
    first_currencies:
#      - btc
    second_currencies:
#      - eth
