general:
  database:
    sqltype: postgresql
    client: psycopg2
    user_name: bjarne
    password: ""
    host: localhost
    port: 5432
    db_name: hochfrequenz
  export:
    export_data_to_csv: false
    csv_dir: /path/where/to/save/csv
  utilities:
    yaml_path: resources/running_exchanges/testing/working/

jobs:
  collecting_ticker:
    yaml_request_name: ticker
    frequency: 1
    exchanges:
      - binance
      - kucoin
      - bibox
      - vindax
    currency_pairs:
    first_currency:
      - btc
      - eth
      - ltc
    second_currency:


#  ticker:
#    yaml_request_name: ticker
#    frequency: 3
#    exchange:
#      - binance
#      - bibox
#    currency_pairs:
#      - first: eth
#        second: btc
#      - first: eth
#        second: doge
#
#    first_currency:
#      - eth
#    second_currency:
