general:
  database:
    sqltype: postgresql
    client: psycopg2
    user_name: postgres
    password: Thw_kiel
    host: localhost
    port: 5432
    db_name: hochfrequenz
  export:
    export_data_to_csv: false
    csv_dir: /Users/bjarne/Desktop/
  utilities:
    yaml_path: resources/running_exchanges/currency_pairs/

updates:
  update_currency_pairs: False

jobs:
  collecting_ticker:
    yaml_request_name: ticker
    frequency: 1
    exchanges:
      - bibox
    currency_pairs:
      - null
    first_currency:
      - BTC
    second_currency:
      - USD

#  ticker:
#    yaml_request_name: ticker
#    frequency: 3
#    exchange:
#      - binance
#      - bibox
#    currency_pairs:
#      - first: eth
#        second: btc
#      - first: eth
#        second: doge
#
#    first_currency:
#      - eth
#    second_currency:

