general:
  database:
    sqltype: postgresql
    client: psycopg2
    user_name: postgres
    password: 1Himmelsrand
    host: localhost
    port: 5432
    db_name: hochfrequenz
  export:
    export_data_to_csv: false
    csv_dir: /Benutzer/pool/Desktop/
  utilities:
    yaml_path: resources/running_exchanges/ticker/

jobs:
  collecting_ticker:
    yaml_request_name: ticker
    frequency: 1
    exchanges:
      - all
    currency_pairs:
    first_currency:
    second_currency:
      - usdt
      - usd


#  ticker:
#    yaml_request_name: ticker
#    frequency: 3
#    exchange:
#      - binance
#      - bibox
#    currency_pairs:
#      - first: eth
#        second: btc
#      - first: eth
#        second: doge
#
#    first_currency:
#      - eth
#    second_currency:

