general:
  database:
    sqltype: postgresql
    client: psycopg2
    user_name: bjarne
    password: ""
    host: localhost
    port: 5432
    db_name: hochfrequenz

  utilities:
    yaml_path: resources/running_exchanges/ #muss noch geändert werden


jobs:
  collecting_ticker:
    yaml_request_name: ticker
    frequency: 1
    exchanges:
      - binance
      - bibox
      - hotbit
      - coinall
      - exx
      - okex
      - vindax
      - whitebit
    currency_pairs:
      - first: btc
        second: eth

    first_currency:
      - btc
    second_currency:
      - btc


  ticker:
    yaml_request_name: ticker
    frequency: 3
    exchanges:
      - binance
      - bibox
    currency_pairs:
      - first: eth
        second: btc
      - first: eth
        second: doge

    first_currency:
      - eth
    second_currency:

