general:
  database:
    sqltype: postgresql
    client: psycopg2
    user_name: bjarne
    password: ""
    host: localhost
    port: 5432
    db_name: hochfrequenz
  operation_settings:
    frequency: 1
  export:
    export_data_to_csv: false
    csv_dir: /path/where/to/save/csv
  utilities:
    yaml_path: resources/running_exchanges/testing/working/
    enable_logging: true

jobs:
#  collecting_ticker:
#    yaml_request_name: ticker
#    exchanges:
#      - exmo
#    currency_pairs:
#      - first: btc
#        second: usd
#      - first: btc
#        second: usdt
#    first_currencies:
#    second_currencies:

  another_one:
    yaml_request_name: historic_rates
    exchanges:
      - bibox
    currency_pairs:
    first_currencies:
      - eth
      - btc
    second_currencies:
      - btc

#  ticker:
#    yaml_request_name: ticker
#    frequency: 3
#    exchange:
#      - binance
#      - bibox
#    currency_pairs:
#      - first: eth
#        second: btc
#      - first: eth
#        second: doge
#
#    first_currency:
#      - eth
#    second_currency:
