general:
  database:
    sqltype: sqlite
    client: psycopg2
    user_name: postgres
    password: Thw_kiel
    host: localhost
    port: 5432
    db_name: test_db
  operation_settings:
    frequency: 0.1
  export:
    export_data_to_csv: true
    csv_dir: resources/csv
  utilities:
    yaml_path: resources/running_exchanges/currency_pairs/
    enable_logging: True

jobs:
 collecting_ticker:
   yaml_request_name: ticker
   update_cp: true
   exchanges:
    - bittrex
   currency_pairs:
   first_currencies:
     - eth #checken, dass es für bittrex nur 4 cps gibt wenn nur eth als first
   second_currencies:

# collecting_rates:
#   yaml_request_name: historic_rates
#   update_cp: False
#   exchanges:
#     - atilly
#   currency_pairs:
#   first_currencies:
#     - eth
#   second_currencies:
