general:
  database:
    sqltype: postgresql
    client: psycopg2
    user_name: bjarne
    password: ''
    host: localhost
    port: 5432
    db_name: hochfrequenz
  operation_settings:
    frequency: 1
  export:
    export_data_to_csv: false
    csv_dir: resources/csv
  utilities:
    yaml_path: resources/running_exchanges/
    enable_logging: false

jobs:
 collecting_ticker:
   yaml_request_name: ticker
   update_cp: true
   exchanges:
    - all
   currency_pairs:
     - first: eos
       second: usd
     - first: eos
       second: usdt
     - first: xrp
       second: usdt
     - first: xrp
       second: usd
     - first: xlm
       second: usdt
     - first: xlm
       second: usd
     - first: neo
       second: usdt
     - first: neo
       second: usd
     - first: btc
       second: usdt
     - first: btc
       second: usd
     - first: eth
       second: usdt
     - first: eth
       second: usd
   first_currencies:
   second_currencies:
