export:
  save_path: resources/csv/
  delimiter: ","

query_options:
  table_name: Ticker
  query_everything: true
  from_timestamp: 01-09-2020 13:20:00
  to_timestamp:
  exchanges:
#    - kucoin
  first_currencies:
#    - eth
  second_currencies:
#    - ngn
  currency_pairs:
#    - first: ltc
#      second: usdt
#    - first: ltc
#      second: bnb
#    - first: btc
#      second: pax