image: "python:3.9.5"

variables:
  MIN_TEST_COVERAGE: 60
  MODULE_PATH: "./crypto_api"

before_script:
  - python --version
  - pip install .
  - export PYTHONPATH="$MODULE_PATH"

stages:
  - static_analysis
  - test

linting:
  stage: static_analysis
  script:
    - pip install pylint
    - shopt -s globstar
    - pylint --disable=R,C0301,W0511,W0613,W0703,E1121,W0614,C0302,E1101,W0401,W1113,W0603 $MODULE_PATH/**/*.py

unit_testing:
  stage: test
  script:
    - pip install pytest
    - pytest -v

unit_testing_coverage:
  stage: test
  script:
    - pip install pytest
    - pip install coverage
    - coverage run -m pytest -v
    - coverage report --fail-under=$MIN_TEST_COVERAGE --include=$MODULE_PATH/* --omit=$MODULE_PATH/tests/*

