image: "python:3.7"

before_script:
  - python --version
  - pip install pylint
  - pip install pytest
  - pip install .

stages:
  - static_analysis
  - test

linting:
  stage: static_analysis
  script:
  - export PYTHONPATH="./crypto_api"
  - shopt -s globstar
  - pylint --disable=R,C0301,W0511,W0613,W0703,E1121 ./crypto_api/**/*.py

unit_testing:
  stage: test
  script:
  - export PYTHONPATH="./crypto_api"
  - pytest -v ./tests
