export:
  delimiter: ","
  decimal: "."

database:
  sqltype: sqlite
  client: psycopg2
  user_name:
  password:
  host: localhost
  port: 5432
  db_name:

query_options:
  table_name: OrderBook
  query_everything: true
  from_timestamp: 01-01-2020 13:20:00
  to_timestamp:
  exchanges:
#    - kucoin
  first_currencies:
#    - eth
  second_currencies:
#    - ngn
  currency_pairs:
#    - first: ltc
#      second: usdt
