logging:
  dirname: /resources/log/
  filename_format: '%Y-%m-%d_%H-%M-%S'
  level: ERROR
  exception_hook: true
request_settings:
  min_return_tuples: 2
  interval_settings: equal_or_lower
  request_direction: 0
