logging:
  dirname: /resources/log/
  filename_format: '%Y-%m-%d_%H-%M-%S'
  level: ERROR
request_settings:
  min_return_tuples: 50
  interval_settings: equal  # equal, lower, higher, lower_or_equal, high_or_equal
  request_direction: 0  # 0: 'horizontal' or 1: 'vertical'

