logging:
  dirname: "/resources/log/"
  filename_format: '%Y-%m-%d_%H-%M-%S'
  level: 'ERROR'  # possible: CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET

request_settings:
  min_return_tuples: 2
  interval_settings: equal_or_lower  # equal, lower, higher, lower_or_equal, high_or_equal
  request_direction: 0  # 0: 'horizontal' i.e. all exchanges at once
                        # 1: 'vertical' i.e. exchange by exchange

