logging:
  dirname: /resources/log/
  filename_format: '%Y-%m-%d_%H-%M-%S'
  level: ERROR  # possible: CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET
  exception_hook: false

request_settings:
  min_return_tuples: 2
  interval_settings: lower_or_equal  # equal, lower, higher, lower_or_equal, high_or_equal


