general:
  database:
    sqltype: sqlite
    client: psycopg2
    user_name: postgres
    password: 1234
    host: localhost
    port: 5432
    db_name: kimchi2
  operation_settings:
    frequency: once
    timeout: 10
  utilities:
    yaml_path: resources/running_exchanges/
    enable_logging: false

jobs:
  Ticker:
    yaml_request_name: order_books
    update_cp: false
    exchanges:
#      - korbit
#      - coinone
#      - coinnest
      - catex
#      - minebit
#      - huobi
#      - gopax
#      - chainx
#      - bitforex
    excluded:

    currency_pairs:
#      - all
      - first: btc
        second: usdt
#      - first: btc
#        second: usdt
#      - first: btc
#        second: krw
##
    first_currencies:
    second_currencies:
