export:
  delimiter: ","

database:
  sqltype: sqlite
  client: psycopg2
  user_name: bjarne
  password:
  host: localhost
  port: 5432
  db_name: test2


query_options:
  table_name: HistoricRate
  query_everything: True
  from_timestamp: 01-09-2020 13:20:00
  to_timestamp:
  exchanges:
#    - kucoin
  first_currencies:
    - Ethereum
  second_currencies:
#    - ngn
  currency_pairs:
#    - first: ltc
#      second: usdt
#    - first: ltc
#      second: bnb
#    - first: btc
#      second: pax